import {ObsClient} from '../recording/obs.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const c=await new ObsClient().connect(),name='Minecraft Agent Lab';
const status=await c.request('GetRecordStatus');if(status.outputActive)throw new Error('OBS busy');
const collections=await c.request('GetSceneCollectionList');if(!collections.sceneCollections.includes(name))await c.request('CreateSceneCollection',{sceneCollectionName:name});else await c.request('SetCurrentSceneCollection',{sceneCollectionName:name});
const profiles=await c.request('GetProfileList');if(!profiles.profiles.includes(name))await c.request('CreateProfile',{profileName:name});else await c.request('SetCurrentProfile',{profileName:name});
for(const [parameterCategory,parameterName,parameterValue] of [['Output','Mode','Simple'],['SimpleOutput','RecQuality','Small'],['SimpleOutput','RecEncoder','nvenc'],['SimpleOutput','RecFormat2','mkv']])await c.request('SetProfileParameter',{parameterCategory,parameterName,parameterValue});
const directory=resolve('.runtime/recordings');await mkdir(directory,{recursive:true});await c.request('SetRecordDirectory',{recordDirectory:directory});
await c.request('SetVideoSettings',{baseWidth:1280,baseHeight:720,outputWidth:1280,outputHeight:720,fpsNumerator:30,fpsDenominator:1});
const scenes=await c.request('GetSceneList');if(!scenes.scenes.some(s=>s.sceneName===name))await c.request('CreateScene',{sceneName:name});
await c.request('SetCurrentProgramScene',{sceneName:name});
const inputs=await c.request('GetInputList');if(!inputs.inputs.some(i=>i.inputName==='Minecraft Window'))await c.request('CreateInput',{sceneName:name,inputName:'Minecraft Window',inputKind:'window_capture',inputSettings:{},sceneItemEnabled:true});
const windows=await c.request('GetInputPropertiesListPropertyItems',{inputName:'Minecraft Window',propertyName:'window'}),window=windows.propertyItems.find(w=>w.itemEnabled&&w.itemValue.includes('GLFW30:javaw.exe'));
if(!window)throw new Error('Minecraft window not found');
await c.request('SetInputSettings',{inputName:'Minecraft Window',inputSettings:{window:window.itemValue,method:2,priority:0,capture_cursor:false,client_area:true},overlay:true});
const item=await c.request('GetSceneItemId',{sceneName:name,sourceName:'Minecraft Window'});
await c.request('SetSceneItemTransform',{sceneName:name,sceneItemId:item.sceneItemId,sceneItemTransform:{positionX:0,positionY:0,boundsType:'OBS_BOUNDS_SCALE_INNER',boundsWidth:1280,boundsHeight:720,boundsAlignment:0}});
const special=await c.request('GetSpecialInputs');for(const inputName of Object.values(special).filter(Boolean))await c.request('SetInputMute',{inputName,inputMuted:true});
await writeFile('.runtime/obs-setup.json',JSON.stringify({profile:name,scene:name,directory,window:window.itemName,video:await c.request('GetVideoSettings')},null,2));
console.log(JSON.stringify({scene:name,directory,window:window.itemName}));c.close();
